name: Bug Report
type: Bug
title: "[bug] "
description: Hunt down one more bug! Please fill with care. 🐞
projects: ["ryse-rs/2"]
body:
  - type: markdown
    attributes:
      value: |
        You've got hawk eyes 🦅

        Make sure title is imperative - actionable - starts with a verb.
        Please acknowledge our [CONTRIBUTING guidelines](https://github.com/ryse-rs/.github/blob/main/CONTRIBUTING.md) and our [GOVERNANCE vision](https://github.com/ryse-rs/.github/blob/main/GOVERNANCE.md).  
        Please fill with care. Accurate and detailed reports speed up resolution and improve outcomes.  
        If you have any questions or need guidance, feel free to add related labels and ping a maintainer.

  - type: textarea
    id: what
    attributes:
      label: 📝 Description
      description: |
        What is the bug? Describe what you expected to happen, and what actually happened.  
        Include error messages, logs, screenshots or clips if relevant.
      placeholder: |
        I expected [X] to happen when I did [Y], but instead [Z] occurred.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔁 Steps to Reproduce
      description: Provide a step-by-step list to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Request inspector displays the following error code: XXX and message '...'
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: 🧪 Environment
      description: |
        Provide related details like OS, browser, tool versions, Rust version, etc.
      placeholder: |
        e.g. Linux 24.04, Chrome 124, Rust 1.85.0, Dioxus 0.7

  - type: textarea
    id: insights
    attributes:
      label: 🧠 Insights
      description: |
        Anything else you’d like to share? Related issues, links, additional information that might help us.  
        Fix proposal or guidance, or tip to avoid this kind of issues.

  - type: markdown
    attributes:
      value: |
        Again, thank you. Every contribution counts! 🙏🏻

        Once the issue submitted, please expand GitHub issue projects right panel and set SCORE values: impact, effort, complexity. →

        Next steps:  
        1. Issue will be reviewed and hypothetically backlogged.
        2. Assignee will create a branch, a pull request, set _status_ to `ACTIVE`, and start working on implementing the task.
