name: Bug Report
type: Bug
title: "[bugfix] "
description: Hunt down one more bug! Please fill with care. 🐞
projects: ["ryse-rs/2"]
body:
  - type: markdown
    attributes:
      value: |
        You've got hawk eyes 🦅

        Please acknowledge our [CONTRIBUTING guidelines](https://github.com/ryse-rs/.github/blob/main/CONTRIBUTING.md) and our [GOVERNANCE vision](https://github.com/ryse-rs/.github/blob/main/GOVERNANCE.md).  
        Please fill this form with care. Accurate and detailed reports speed up resolution and improve outcomes.  
        If you have any questions or need guidance, feel free to add related labels and ping a maintainer.

  - type: textarea
    id: what
    attributes:
      label: What is the issue?
      description: Expected behaviour vs Current behaviour.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: input
    id: context
    attributes:
      label: Environment
      description: Relevant information about your environment (e.g. browser, OS, versions of rust, tool, etc.).
  - type: textarea
    id: how
    attributes:
      label: How can we fix it?
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.

  - type: markdown
    attributes:
      value: |
        Again, thank you. Every contribution counts! 🙏🏻

        Once the issue submitted, please expand GitHub issue projects right panel and set SCORE values: impact, effort, complexity.
