name: Feature Request
type: Feature
title: "[feature] "
description: Thank you for contributing! Your passion is greatly appreciated. 🙏🏻
projects: ["ryse-rs/2"]
body:
  - type: markdown
    attributes:
      value: |
        💜 Thank you for your interest in improving the project!

        Make sure title is imperative - actionable - starts with a verb.
        Please acknowledge our [CONTRIBUTING guidelines](https://github.com/ryse-rs/.github/blob/main/CONTRIBUTING.md) and our [GOVERNANCE vision](https://github.com/ryse-rs/.github/blob/main/GOVERNANCE.md).  
        Please fill with care. Accurate and detailed reports speed up resolution and improve outcomes.  
        If you have any questions or need guidance, feel free to add related labels and ping a maintainer.

  - type: input
    id: what
    attributes:
      label: ✨ What would you like to see added or improved?
      description: Feature summary. Focus on what, not how.
      placeholder: e.g. "Support for nested schema preview in editor".
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why should we do that?
      description: Who needs this, and what problem does it solve?
      placeholder: |
        Right now, [X] is hard to do or limited.
        This feature would improve [Y] for [type of user].
    validations:
      required: true

  - type: textarea
    id: how
    attributes:
      label: 🛠️ How could this be implemented or integrated?
      description: |
        Feel free to provide implementation details.  
        Use checklists or pseudocode if helpful.  
        Include links, related issues, prior art, theory, designs, or any supporting materials.
      value: "- [ ]"

  - type: markdown
    attributes:
      value: |
        Again, thank you. Every contribution counts! 🙏🏻

        Once the issue submitted, please expand GitHub issue projects right panel and set SCORE values: impact, effort, complexity. →

        Next steps:  
        1. Issue will be reviewed and hypothetically backlogged.
        2. Assignee will create a branch, a pull request, set _status_ to `ACTIVE`, and start working on implementing the task.
