name: Tweak Request
type: Task
description: Thank you for contributing to this project! Your efforts are greatly appreciated. 🙏🏻
title: "[tweak] "
projects: ["ryse-rs/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your dedication 🦖

        Please acknowledge our [CONTRIBUTING guidelines](https://github.com/ryse-rs/.github/blob/main/CONTRIBUTING.md) and our [GOVERNANCE vision](https://github.com/ryse-rs/.github/blob/main/GOVERNANCE.md).  
        Please fill this form with care. Accurate and detailed reports speed up resolution and improve outcomes.  
        If you have any questions or need guidance, feel free to add related labels and ping a maintainer.

  - type: textarea
    id: what
    attributes:
      label: What would this change?
      description: Current situation vs new situation. Context, to help understand your proposal.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why should we do that?
      description: What would be the benefits?
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: How can we achieve this?
      description: Feel free to provide implementation details. This will speed up the process.

  - type: markdown
    attributes:
      value: |
        Again, thank you. Every contribution counts! 🙏🏻

        Once the issue submitted, please expand GitHub issue projects right panel and set SCORE values: impact, effort, complexity.
