name: Task Request
type: Task
title: "[task] "
description: Thank you for contributing to this project! Your efforts are greatly appreciated. 🙏🏻
projects: ["ryse-rs/2"]
body:
  - type: markdown
    attributes:
      value: |
        🦖 Thank you for helping improve the project!

        Make sure title is imperative - actionable - starts with a verb.
        Please acknowledge our [CONTRIBUTING guidelines](https://github.com/ryse-rs/.github/blob/main/CONTRIBUTING.md) and our [GOVERNANCE vision](https://github.com/ryse-rs/.github/blob/main/GOVERNANCE.md).  
        Please fill with care. Accurate and detailed reports speed up resolution and improve outcomes.  
        If you have any questions or need guidance, feel free to add related labels and ping a maintainer.

  - type: textarea
    id: what
    attributes:
      label: 🧭 What should be done?
      description: Current situation vs new situation. Context, to help understand your proposal.
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: 🎯 Why is this task important?
      description: What problem does it solve? Who benefits from it?
      placeholder: |
        This would improve [X] because...
        It enables [Y] to be done faster/more reliably.
    validations:
      required: true

  - type: textarea
    id: how
    attributes:
      label: 🛠️ How could this be implemented or integrated?
      description: |
        Feel free to provide technical suggestions, implementation details.
        Use checklists or pseudocode if helpful.  
        Include links, theory, or any supporting materials.
      placeholder: |
        - [ ] Create a new module in ...
        - [ ] Reuse helper from ...
        - [ ] Add a test in ...

  - type: markdown
    attributes:
      value: |
        Again, thank you. Every contribution counts! 🙏🏻

        Once the issue submitted, please expand GitHub issue projects right panel and set SCORE values: impact, effort, complexity. →

        Next steps:  
        1. Issue will be reviewed and hypothetically backlogged.
        2. Assignee will create a branch, a pull request, set _status_ to `ACTIVE`, and start working on implementing the task.
