name: Production Bug Report
type: Bug
description: 🚨 URGENT - RELEASE BUG! Please fill with care. 🐞
title: "[hotfix] "
labels: ["HOTFIX"]
projects: ["ryse-rs/2"]
body:
  - type: markdown
    attributes:
      value: |
        Our testing must be improved 🧪

        Please acknowledge our [CONTRIBUTING guidelines](https://github.com/ryse-rs/.github/blob/main/CONTRIBUTING.md) and our [GOVERNANCE vision](https://github.com/ryse-rs/.github/blob/main/GOVERNANCE.md).  
        Please fill this form with care. Accurate and detailed reports speed up resolution and improve outcomes.  
        If you have any questions or need guidance, feel free to add related labels and ping a maintainer.

  - type: textarea
    id: what
    attributes:
      label: What is the issue?
      description: Expected behavior vs Current behavior.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Environment
      description: e.g. browser, OS, versions of rust, tool, etc.

  - type: textarea
    id: other
    attributes:
      label: Intel
      description: Propose a fix, paste log output, or provide any other relevant information.

  - type: markdown
    attributes:
      value: |
        Again, thank you. Every contribution counts! 🙏🏻

        Once the issue submitted, please expand GitHub issue projects right panel and set SCORE values: impact, effort, complexity.
