name: Simple, immediate changes. Self-assigned
type: Task
description: doc or test or minor and immediate changes only!
projects: ["ryse-rs/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your quickness 🗲

        Please acknowledge our [CONTRIBUTING guidelines](https://github.com/ryse-rs/.github/blob/main/CONTRIBUTING.md) and our [GOVERNANCE vision](https://github.com/ryse-rs/.github/blob/main/GOVERNANCE.md).  
        Please fill this form with care. Accurate and detailed reports speed up resolution and improve outcomes.  
        If you have any questions or need guidance, feel free to add related labels and ping a maintainer.

  - type: textarea
    id: what
    attributes:
      label: What are you proposing?
      description: Current situation vs new situation. Provide context, to help understand your proposal.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Again, thank you. Every contribution counts! 🙏🏻

        Once the issue submitted:
        1. Please assign yourself
        2. Please expand GitHub issue projects right panel and set SCORE values: impact, effort, complexity.
