name: Rapport de bug (FR)
description: Soumettre un rapport de bug en suivant notre méthodologie
title: "[bug] ..."
labels: ["bug"]
projects: ["ryse-rs/2"]
body:
  - type: markdown
    attributes:
      value: |
        ### Merci de prendre le temps de remplir ce rapport de bug ! 🐞

        > [!IMPORTANT]  
        > Veuillez remplir ce formulaire avec soin. Les rapports prêts à être traités sont prioritaires.

        > [!TIP]
        > Si vous avez des questions ou besoin d'aide, n'hésitez pas à ajouter des étiquettes pertinentes et à mentionner un mainteneur.

        - [ ] Une fois que vous estimez que ce problème est prêt à être traité, définissez son _statut_ sur `PROCESS` et attendez que le statut soit mis à jour sur `BACKLOG` avant de commencer la mise en œuvre.
        - [ ] Je souhaite résoudre cela moi-même.

        <details>
        <summary>
          
        ## RÈGLES POUR LES CONTRIBUTEURS - À l'attention de l'assigné

        </summary>

        > ❗ _Ignorez ce qui suit si vous ne prévoyez pas de résoudre cela vous-même._ ❗
        ### 𝟏 - Si vous souhaitez résoudre cela vous-même
        - [ ] Vous attribuer vous-même le problème
        - [ ] Proposer une solution dans la description / les commentaires du problème.
        - [ ] Définir le _statut_ approprié : `BACKLOG` (si prêt) ou `REFINE` (si ce n'est pas clair) ou `ACTIVE` (si vous travaillez réellement sur la mise en œuvre)
        - [ ] Créer une branche depuis le panneau de développement GitHub et commencer à travailler dessus.
        ### 𝟐 - Règles de mise en œuvre
        - [ ] Noter vos choix de conception / mise en œuvre. Ce qui a fonctionné, ce qui n'a pas fonctionné ou ne fonctionnerait pas, pourquoi vous avez choisi ceci plutôt que cela.
        - [ ] Implémenter des tests unitaires et/ou d'intégration approfondis pour le code nouvellement ajouté et sécuriser la racine du problème actuel. Ou justifier pourquoi ils ne sont pas nécessaires dans les commentaires.
        - [ ] Rédiger la documentation requise pour le code nouvellement ajouté.
        ### 𝟑 - Une fois le travail de mise en œuvre terminé
        - [ ] Créer une demande de pull depuis votre branche.
        - [ ] Définir le _statut_ du problème sur `REVIEW`.
        - [ ] Demander une revue à un mainteneur. Une fois la revue effectuée, effectuer un rebase de la branche principale sur votre branche (si nécessaire).

        > _status_es: NEW REFINE PROCESS BACKLOG ACTIVE TEST REVIEW CHANGES REBASE DONE CANCELLED

        </details>
  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportement attendu
      description: Une description claire et concise de ce à quoi vous vous attendiez.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Comportement actuel
      description: Une description claire et concise de ce que vous rencontrez.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Étapes pour reproduire
      value: |
        1. ...
        2. ...
    validations:
      required: true
  - type: input
    id: context
    attributes:
      label: Environnement
      description: Veuillez fournir toutes les informations pertinentes sur votre environnement (par exemple, navigateur, système d'exploitation, versions, etc.).
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Sortie de journal pertinente
      description: Veuillez copier et coller toute sortie de journal pertinente. Cela sera automatiquement formaté en code, donc pas besoin de guillemets inversés.
      render: shell

# SYSTÈME DE NOTATION, COMMUN À TOUS LES MODÈLES
  - type: markdown
    attributes:
      value: |
        ## RÈGLES DE PRIORISATION - SYSTÈME DE NOTATION
        > [!NOTE]
        > __Formule de priorité__ ➧ `impact * effort * complexité`
        > __Formule de contribution__ ➧ `impact * 0.5 * complexité * (effort réellement fusionné)`
        > L'effort est calculé de la manière suivante : `max(ajouts, suppressions)`
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: Combien d'utilisateurs sont affectés et quelle est la gravité de l'impact ? `moyenne(portée, impact)`
      options:
        - I.1. Impact négligeable | Affecte très peu d'utilisateurs
        - I.2. Affecte une partie spécifique de l'application, mais pas critique | Affecte un petit nombre d'utilisateurs
        - I.3. Affecte une partie centrale de l'application | Affecte un grand nombre d'utilisateurs
        - I.4. Rien ne fonctionne | Chaque utilisateur est affecté
    validations:
      required: true
  - type: dropdown
    id: effort
    attributes:
      label: Effort
      description: Sélectionnez le nombre estimé de lignes de code `max(ajouts, suppressions)`. Ne tenez pas compte de la complexité.
      options:
        - "E.1. -200 LdC"
        - "E.2. -750 LdC"
        - "E.3. -1k5 LdC"
        - "E.4. +1k5 LdC"
    validations:
      required: true
  - type: dropdown
    id: complexity
    attributes:
      label: Complexité
      description: À quel point pensez-vous que la résolution du problème sera complexe ? Prenez en compte des facteurs tels que l'algorithmie, la difficulté et l'incertitude. Ne tenez pas compte du nombre de lignes de code.
      options:
        - C.1. Facile. L'utilisation des cellules cérébrales est principalement nulle.
        - C.2. Gérable. Nécessitera des heures de recherche / expérimentation.
        - C.3. Difficile. Nécessitera des jours de recherche / expérimentation, __avant la mise en œuvre__.
        - C.4. Niveau de magie noire. Peut nécessiter des semaines de recherche / expérimentation, __avant la mise en œuvre__. Peut même être insoluble.
    validations:
      required: true
