name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "raw"]
projects: ["ryse-rs/2"]
body:
  - type: markdown
    attributes:
      value: "**NOTE** To the attention of anyone willing to fix this bug (may be you!)"
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > To the attention of anyone willing to fix this bug (may be you!)
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        **NOTE**
        To the attention of anyone willing to fix this bug (may be you!) [!NOTE]
        - [ ] Self-assign the issue
        - [ ] Propose a solution in the issue description / comments.
        - [ ] if the resolution implies design changes, set the status to "TO CLARIFY" and wait for the status to be updated to `TODO` before you start the implementation. Else, tick and go next.
        - [ ] Create a branch from the GitHub development panel and immediately create a Pull Request from that branch.
        Once done working on the implementation:
        - [ ] Rebase main in your branch (if needed).
        - [ ] Request a maintainer review from the PR.
        Please make sure:
        - [ ] To write down your design / implementation choices. What worked, what did not or would not, why you chose this over that.
        - [ ] To implement extensive unit and/or integration tests to newly added code and to secure the root of the current issue. Or justify why they are not needed in the comments
        - [ ] To write required documentation to newly added code
        [!NOTE] If you have any questions or need guidance, feel free to add related labels and ping a maintainer [!NOTE]
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Environment
      description: Please provide any relevant information about your environment (e.g. browser, OS, versions etc.).
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

# SCORING SYSTEM, COMMON TO ALL TEMPLATES
  - type: markdown
    attributes:
      value: |
        ## SCORING
        [!NOTE]
          Priority Formula: _impact * effort * complexity_
          Contribution Formula: _impact * 0.5 * complexity * (actually merged) effort_.
          Effort being computed this way: max(additions, deletions)
        [!NOTE]
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How many users are affected and how severe is the impact? `average(reach, impact)`
      options:
        - Negligible impact | Affects really few users
        - Affects a specific part of the application, but not critical | Affects a small number of users
        - Affects a core part of the application | Affects a large number of users
        - Nothing works | Every user is affected
    validations:
      required: true
  - type: dropdown
    id: effort
    attributes:
      label: Effort
      description: Select the estimated number of lines of code `max(additions, deletions)`. Do not take complexity into account.
      options:
        - "-200 LoC"
        - "-750 LoC"
        - "-1k5 LoC"
        - "+1k5 LoC"
    validations:
      required: true
  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      description: How complex do you think the problem resolution will be? Consider factors such as algorithmic, brainfuck, and uncertainty. Do not take lines of code into account
      options:
        - Easy. Use of brain cells is mostly null.
        - Manageable. Will require hours of research / experimentation.
        - Hard. Will require days of research / experimentation, __prior to implementation__.
        - Black Magic level. May require weeks of research / experimentation, __prior to implementation__. May even be unsolvable.
    validations:
      required: true

