name: Enhancement Request
description: Propose an improvement following our methodology
title: "[enhance] ..."
labels: ["enhancement"]
projects: ["ryse-rs/2"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for your contribution to enhancing this project. Your efforts are greatly appreciated. ðŸ™ðŸ»
        > [!IMPORTANT]  
        > Please fill this form with care. Ready to process requests are prioritized.

        > [!TIP]
        > If you have any questions or need guidance, feel free to add related labels and ping a maintainer

        - [ ] Once you consider this issue ready to be processed, set its status to `PROCESS` and wait for the status to be updated to `BACKLOG` before you start the implementation.
        - [ ] I'd like to implement this myself.
        
        <details>
        <summary>

        ## CONTRIBUTOR RULES - To the attention of the assignee

        </summary>

        > â— _Ignore the following if you are not going to implement this enhancement yourself._ â—
        ### ðŸ - If you want to implement this enhancement yourself
        - [ ] Self-assign the issue
        - [ ] Propose a solution in the issue description / comments.
        - [ ] Set the appropriate _status_: `BACKLOG` (if ready) or `REFINE` (if not clear) or `ACTIVE` (if actually working on the implementation)
        - [ ] Create a branch from the GitHub development panel and start working on it.
        ### ðŸ - Implementation rules
        - [ ] Have your design / implementation choices been written down in comments? What worked, what did not or would not, why you chose this over that.
        - [ ] Have you implemented unit and/or integration tests? Or justify why they are not needed in the comments.
        - [ ] Have you written documentation? Make sure anyone else working over your code can understand it.
        - [ ] Make sure to create a new issue for any future __expected__ improvement and reference this one in the new issue description.
        ### ðŸ‘ - Once done working on the implementation
        - [ ] Create a Pull Request from your branch.
        - [ ] Set the _status_ of the issue to `REVIEW`.
        - [ ] Request the review from a maintainer. Once reviewed, rebase main in your branch (if needed).

        > _status_es: NEW REFINE PROCESS BACKLOG ACTIVE TEST REVIEW CHANGES REBASE DONE CANCELLED

        </details>


  - type: markdown
    attributes:
      value: |
        # ENHANCEMENT REQUEST RULES
  - type: textarea
    id: current-situation
    attributes:
      label: Describe the current situation and what could be improved.
      description: Quickly define the current context, to help understand your proposal. Briefly describe what could be improved.
      placeholder: |
        Example.
        Right now, `.env` does not set environment variables, the file is parsed as-is by the `serde-toml` crate dependency.
        But environment variables could help a lot with CI and containers, remove the need of a dependency, and (maybe) simplify code.
      value: |
        __The current situation__:
        __The new situation__:
        __The __:
    validations:
      required: true
  - type: input
    id: new-situation
    attributes:
      label: Describe your proposition - the new situation
      description: WHAT can be improved? Only describe the final state, not the process, not a comparison.
      placeholder: Example. Use environment variables, which would be set using rust builtin .cargo/config.toml file.
    validations:
      required: true
  - type: input
    id: what
    attributes:
      label: What is the end goal?
      description: What needs are you trying to fulfill? Do not describe the benefits, only the goal.
      placeholder: Example. Better integration with other tools and even within the program.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: List the benefits over what we currently have
      placeholder: |
        ~ We could merge CLI parameters with current .env variables.
        - We could set environment variables in a github actions context
        - We could set environment variables in a docker context
        - Bonus - one less dependency to use (removal of `serde-toml`)
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: HOW to achieve this? Implementation details
      description: Feel free to provide implementation details. This will speed up the process.
      value: |
        ```rust
        // Structure content, Traits, patterns, relations between entities, etc.
        ```

# SCORING SYSTEM, COMMON TO ALL TEMPLATES
  - type: markdown
    attributes:
      value: |
        ## PRIORIZATION RULES - SCORING SYSTEM
        > [!NOTE]
        > __Priority Formula__ âž§ `impact * effort * complexity`
        > __Contribution Formula__ âž§ `impact * 0.5 * complexity * (actually merged) effort`
        > Effort being computed this way: `max(additions, deletions)`
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How many users would benefit from this enhancement and how big would the impact be? `average(reach, impact)`
      options:
        - I.1. Negligible impact | Benefits really few users
        - I.2. Interesting enhancement | Benefits a fair proportion of users
        - I.3. Non-blocking but essential enhancement | Every user will benefit from having this enhancement.
        - I.4. This enhancement is a prerequisite for other essential enhancements | Would have no user without this enhancement.
    validations:
      required: true
  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      description: How complex do you think the problem resolution will be? Consider factors such as algorithmic, brainfuck, novelty, experimentation and uncertainty. Do not take lines of code into account
      options:
        - C.1. Easy. Use of brain cells is mostly null.
        - C.2. Manageable. Will require hours of research / experimentation.
        - C.3. Hard. Will require days of research / experimentation, __prior to implementation__.
        - C.4. Black Magic level. May require weeks of research / experimentation, __prior to implementation__. May even be unsolvable.
    validations:
      required: true
  - type: dropdown
    id: effort
    attributes:
      label: Effort
      description: Select the estimated number of lines of code `max(additions, deletions)`. Do not take complexity into account.
      options:
        - "E.1. -200 LoC"
        - "E.2. -750 LoC"
        - "E.3. -1k5 LoC"
        - "E.4. +1k5 LoC"
    validations:
      required: true
