name: Demande d'amélioration
description: Proposez une amélioration en suivant notre méthodologie
title: "[enhance] ..."
labels: ["enhancement"]
projects: ["ryse-rs/2"]
body:
  - type: markdown
    attributes:
      value: |
        ### Merci pour votre contribution à l'amélioration de ce projet. Vos efforts sont grandement appréciés. 🙏🏻
        > [!IMPORTANT]  
        > Veuillez remplir ce formulaire avec soin. Les demandes prêtes à être traitées sont prioritaires.

        > [!TIP]
        > Si vous avez des questions ou besoin d'aide, n'hésitez pas à ajouter des étiquettes pertinentes et à mentionner un mainteneur.

        - [ ] Une fois que vous considérez que cette demande est prête à être traitée, définissez son statut sur `PROCESS` et attendez que le statut soit mis à jour sur `BACKLOG` avant de commencer la mise en œuvre.
        - [ ] Je souhaite implémenter cela moi-même.
        
        <details>
        <summary>

        ## RÈGLES POUR LES CONTRIBUTEURS - À l'attention du développeur assigné

        </summary>

        > ❗ _Ignorez ce qui suit si vous ne prévoyez pas d'implémenter cette amélioration vous-même._ ❗
        ### 𝟏 - If you want to implement this enhancement yourself
        - [ ] Self-assign the issue
        - [ ] Propose a solution in the issue description / comments.
        - [ ] Set the appropriate _status_: `BACKLOG` (if ready) or `REFINE` (if not clear) or `ACTIVE` (if actually working on the implementation)
        - [ ] Create a branch from the GitHub development panel and start working on it.
        ### 𝟐 - Implementation rules
        - [ ] Have your design / implementation choices been written down in comments? What worked, what did not or would not, why you chose this over that.
        - [ ] Have you implemented unit and/or integration tests? Or justify why they are not needed in the comments.
        - [ ] Have you written documentation? Make sure anyone else working over your code can understand it.
        - [ ] Make sure to create a new issue for any future __expected__ improvement and reference this one in the new issue description.
        ### 𝟑 - Once done working on the implementation
        - [ ] Create a Pull Request from your branch.
        - [ ] Set the _status_ of the issue to `REVIEW`.
        - [ ] Request the review from a maintainer. Once reviewed, rebase main in your branch (if needed).

        > _status_es: NEW REFINE PROCESS BACKLOG ACTIVE TEST REVIEW CHANGES REBASE DONE CANCELLED

        </details>
  - type: markdown
    attributes:
      value: |
        # RÈGLES POUR LES DEMANDES D'AMÉLIORATION
  - type: textarea
    id: added-value
    attributes:
      label: Pourquoi avons-nous besoin de cette amélioration ? Quelle serait la valeur ajoutée pour le produit ?
      description: La motivation - POURQUOI
    validations:
      required: true
  - type: textarea
    id: need
    attributes:
      label: Veuillez lister les éléments à intégrer/améliorer.
      description: Le besoin - QUOI. Notez que cette liste doit être régulièrement mise à jour.
      value: |
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: information
    attributes:
      label: N'hésitez pas à fournir toute information supplémentaire qui pourrait nous aider à comprendre le contexte de cette demande.
  - type: textarea
    id: implementation
    attributes:
      label: Pour les développeurs - N'hésitez pas à fournir les détails de votre implémentation idéale. Cela accélérera le processus.
      placeholder: Contenu de la structure, traits, modèles, relations entre les entités, etc.

# SYSTÈME DE NOTATION, COMMUN À TOUS LES MODÈLES
  - type: markdown
    attributes:
      value: |
        ## RÈGLES DE PRIORISATION - SYSTÈME DE NOTATION
        > [!NOTE]
        > __Formule de priorité__ ➧ `impact * effort * complexité`
        > __Formule de contribution__ ➧ `impact * 0.5 * complexité * (effort réellement fusionné)`
        > L'effort est calculé de la manière suivante : `max(ajouts, suppressions)`
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: Combien d'utilisateurs bénéficieraient de cette amélioration et quel serait l'impact ? `moyenne(portée, impact)`
      options:
        - I.1. Impact négligeable | Bénéficie à très peu d'utilisateurs
        - I.2. Amélioration intéressante | Bénéficie à une proportion équitable d'utilisateurs
        - I.3. Amélioration non bloquante mais essentielle | Chaque utilisateur bénéficiera de cette amélioration.
        - I.4. Cette amélioration est une condition préalable à d'autres améliorations essentielles | Il n'y aurait aucun utilisateur sans cette amélioration.
    validations:
      required: true
  - type: dropdown
    id: complexity
    attributes:
      label: Complexité
      description: À quel point pensez-vous que la résolution du problème sera complexe ? Prenez en compte des facteurs tels que l'algorithmie, l'exploration et l'incertitude. Ne tenez pas compte des lignes de code.
      options:
        - C.1. Facile. L'utilisation des cellules cérébrales est principalement nulle.
        - C.2. Gérable. Nécessitera des heures de recherche / expérimentation.
        - C.3. Difficile. Nécessitera des jours de recherche / expérimentation, __avant la mise en œuvre__.
        - C.4. Niveau de Magie Noire. Peut nécessiter des semaines de recherche / expérimentation, __avant la mise en œuvre__. Peut même être insoluble.
    validations:
      required: true
  - type: dropdown
    id: effort
    attributes:
      label: Effort
      description: Pour les développeurs - Sélectionnez le nombre estimé de lignes de code `max(ajouts, suppressions)`. Ne tenez pas compte de la complexité.
      options:
        - "E.1. -200 lignes de code"
        - "E.2. -750 lignes de code"
        - "E.3. -1k5 lignes de code"
        - "E.4. +1k5 lignes de code"
    validations:
      required: true
