name: Demande de fonctionnalité
description: Proposez une nouvelle fonctionnalité en suivant notre méthodologie
title: "[feat] ..."
labels: ["feature"]
projects: ["ryse-rs/2"]
body:
  - type: markdown
    attributes:
      value: |      
        ### Merci pour votre contribution à l'amélioration de ce projet. Vos efforts sont grandement appréciés. 🙏🏻
        > [!IMPORTANT]  
        > Veuillez remplir ce formulaire avec soin. Les demandes prêtes à être traitées sont prioritaires.

        > [!TIP]
        > Si vous avez des questions ou avez besoin d'aide, n'hésitez pas à ajouter des étiquettes pertinentes et à mentionner un mainteneur.

        - [ ] Une fois que vous estimez que cette demande est prête à être traitée, définissez son statut sur `PROCESS` et attendez que le statut soit mis à jour sur `BACKLOG` avant de commencer la mise en œuvre.
        - [ ] Je souhaite implémenter cela moi-même.
        
        <details>
        <summary>

        ## RÈGLES POUR LES CONTRIBUTEURS - À l'attention de l'assigné

        </summary>

        > ❗ _Ignorez ce qui suit si vous ne prévoyez pas d'implémenter cette fonctionnalité vous-même._ ❗
        ### 𝟏 - Si vous souhaitez implémenter cette fonctionnalité vous-même
        - [ ] Auto-assignez-vous l'issue
        - [ ] Proposez une solution dans la description / les commentaires de l'issue.
        - [ ] Définissez le _statut_ approprié : `BACKLOG` (si prêt) ou `REFINE` (si ce n'est pas clair) ou `ACTIVE` (si vous travaillez réellement sur la mise en œuvre)
        - [ ] Créez une branche (à partir du panneau de développement GitHub à droite) et créez immédiatement une demande de pull à partir de cette branche.
        ### 𝟐 - Règles d'implémentation
        - [ ] Vos choix de conception / implémentation ont-ils été consignés dans des commentaires ? Ce qui a fonctionné, ce qui n'a pas fonctionné ou ne fonctionnerait pas, pourquoi vous avez choisi ceci plutôt que cela.
        - [ ] Avez-vous implémenté des tests unitaires et/ou d'intégration ? Ou justifiez pourquoi ils ne sont pas nécessaires dans les commentaires.
        - [ ] Avez-vous rédigé une documentation ? Assurez-vous que toute autre personne travaillant sur votre code puisse le comprendre.
        - [ ] Assurez-vous de créer une nouvelle issue pour toute amélioration future __attendue__ et référencez celle-ci dans la description de la nouvelle issue.
        ### 𝟑 - Une fois que vous avez terminé de travailler sur l'implémentation
        - [ ] Créez une demande de pull à partir de votre branche.
        - [ ] Définissez le _statut_ de l'issue sur `REVIEW`.
        - [ ] Demandez une revue à un mainteneur. Une fois la revue terminée, effectuez un rebase de la branche principale sur votre branche (si nécessaire).

        </details>
  - type: markdown
    attributes:
      value: |
        # RÈGLES POUR LES DEMANDES DE FONCTIONNALITÉ
  - type: input
    id: target
    attributes:
      label: Pour qui cette fonctionnalité est-elle destinée ? / Qui en bénéficierait directement ?
      description: Veuillez fournir une réponse qualifiée. `Les utilisateurs` n'est pas une réponse qualifiée.
      placeholder: Le rôle - QUI
    validations:
      required: true
  - type: textarea
    id: added-value
    attributes:
      label: Quels besoins de la cible cette fonctionnalité adresse-t-elle ? Quelle est la valeur ajoutée attendue pour le produit ?
      description: Cela peut inclure des fonctionnalités, des améliorations de performance ou tout autre résultat qui aura un impact direct sur l'expérience des utilisateurs avec le produit.
      placeholder: La motivation - POURQUOI
    validations:
      required: true
  - type: textarea
    id: information
    attributes:
      label: N'hésitez pas à fournir des informations supplémentaires qui pourraient nous aider à comprendre le contexte de cette demande de fonctionnalité.
  - type: textarea
    id: need
    attributes:
      label: Veuillez établir une liste de tâches complète.
      description: Le besoin - QUOI. Notez que cette liste doit être régulièrement mise à jour.
      value: |
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: N'hésitez pas à fournir les détails de votre implémentation idéale. Cela accélérera le processus.
      placeholder: Contenu de la structure, traits, modèles, relations entre les entités, etc.

# SYSTÈME DE NOTATION, COMMUN À TOUS LES MODÈLES
  - type: markdown
    attributes:
      value: |
        ## RÈGLES DE PRIORISATION - SYSTÈME DE NOTATION
        > [!NOTE]
        > __Formule de priorité__ ➧ `impact * effort * complexité`
        > __Formule de contribution__ ➧ `impact * 0.5 * complexité * (effort réellement fusionné)`
        > L'effort est calculé de la manière suivante : `max(ajouts, suppressions)`
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: Combien d'utilisateurs bénéficieraient de cette fonctionnalité et quel serait l'impact ? `moyenne(portée, impact)`
      options:
        - I.1. Impact négligeable | Bénéficie à très peu d'utilisateurs
        - I.2. Fonctionnalité intéressante | Bénéficie à une proportion équitable d'utilisateurs
        - I.3. Fonctionnalité essentielle mais non bloquante | Chaque utilisateur bénéficiera de cette fonctionnalité.
        - I.4. Cette fonctionnalité est une condition préalable à d'autres fonctionnalités essentielles | Il n'y aurait pas d'utilisateur sans cette fonctionnalité.
    validations:
      required: true
  - type: dropdown
    id: effort
    attributes:
      label: Effort
      description: Sélectionnez le nombre estimé de lignes de code `max(ajouts, suppressions)`. Ne tenez pas compte de la complexité.
      options:
        - "E.1. -200 lignes de code"
        - "E.2. -750 lignes de code"
        - "E.3. -1k5 lignes de code"
        - "E.4. +1k5 lignes de code"
    validations:
      required: true
  - type: dropdown
    id: complexity
    attributes:
      label: Complexité
      description: À quel point pensez-vous que la résolution du problème sera complexe ? Prenez en compte des facteurs tels que l'algorithmie, la difficulté et l'incertitude. Ne tenez pas compte du nombre de lignes de code.
      options:
        - C.1. Facile. L'utilisation des cellules cérébrales est presque nulle.
        - C.2. Gérable. Nécessitera des heures de recherche / expérimentation.
        - C.3. Difficile. Nécessitera des jours de recherche / expérimentation, __avant l'implémentation__.
        - C.4. Niveau de magie noire. Peut nécessiter des semaines de recherche / expérimentation, __avant l'implémentation__. Peut même être insoluble.
    validations:
      required: true
